### ISSUE TITLE
Error with webdriver.Chrome

### ISSUE THREAD

**Issue by Mrodent** [uNickz/WebSite2PDF#4]
```
>>> import WebSite2PDF
>>>
>>> url = "https://pypi.org"
>>>
>>> c = WebSite2PDF.Client()
>>> with open("file_name.pdf", "wb+") as file:
...     file.write(c.pdf(url))
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "D:\apps\Python\virtual_envs\website2pdf\lib\site-packages\WebSite2PDF\client.py", line 48, in pdf
    self.client.start_client(__opts)
  File "D:\apps\Python\virtual_envs\website2pdf\lib\site-packages\WebSite2PDF\driver\driver.py", line 29, in start_client
    self.driver = webdriver.Chrome(executable_path = ChromeDriverManager().install(), options = options, service = service)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
```

From the non-response and date of the earlier issue it doesn't look like you care very much that your project isn't working.

**Comment by uNickz** [comment]
Issue Fixed! (Thank you for the report and sorry for the wait)

Added support for the new versions of Selenium >= 4.10.0. (https://github.com/SeleniumHQ/selenium/commit/9f5801c82fb3be3d5850707c46c3f8176e3ccd8e)

Download the library again with:
``` bash
pip3 install -U git+https://github.com/uNickz/WebSite2PDF
```
